### ISSUE TITLE
Use Lombok @Data annotations

### ISSUE THREAD

**Issue by michal-niedzwiedzki** [jakpop/user-rest-api#12]
https://github.com/jakpop/user-rest-api/blob/bc96cd4788e5ea7819b61eb0538604ba72fe6a8c/src/main/java/com/example/userrestapi/User.java#L19

Lombok provides handy `@Data` annotation that eliminates the need of explicit getters and setters.

**Comment by pandaive** [comment]
Info about lombok: https://projectlombok.org/
if you're using IDE like eclipse or intellij, you will need to install a lombok plugin and enable annotation processing
otherwise it's enough to add it as a dependency in your project
I don't think that it's that important thought, but it's a nice to have tool :)
